version: "3"
services:
  inditex-pvp-servlet:
    image: inditex-pvp-servlet-parent:0.0.1-SNAPSHOT
    ports: 
      - "8881:8881"
    environment:
      ENV: local
      DB_URI: jdbc:h2:mem:inditex;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1

  inditex-pvp-reactive:
    image: inditex-pvp-reactive:0.0.1-SNAPSHOT
    ports: 
      - "8882:8882"
    environment:
      ENV: local
      R2DBC_URI: r2dbc:h2:mem:///inditex;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1
      JDBC_URI: jdbc:h2:mem:inditex;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1
