server:
  port: 8081
  shutdown: graceful
  compression:
    enabled: true

spring:
  application:
    name: itx-pvp-servlet

  datasource:
    url: ${DB_URI}

  jpa:
    hibernate:
      ddl-auto: none
    database: h2

  flyway:
    baseline-on-migrate: true
    locations: classpath:/db/migrations/common,classpath:/db/migrations/${ENV:pro}


management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    root: ${LOG_LEVEL_ROOT}
    com.diegosaldiaz.inditex.pvp: ${LOG_LEVEL_ITX_PVP}
    org.springframework: ${LOG_LEVEL_SPRING_FRAMEWORK}
    org.hibernate.SQL: ${LOG_LEVEL_HIBERNATE_SQL}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOG_LEVEL_HIBERNATE_BASIC_BINDER}
