server:
  port: 8082
  shutdown: graceful
  compression:
    enabled: true

spring:
  application:
    name: itx-pvp-reactive

  r2dbc:
    # url: ${R2DBC_URI}
    url: r2dbc:h2:file:///./tmp/inditex

  flyway:
    # url: ${JDBC_URI}
    url: jdbc:h2:file:./tmp/inditex
    baseline-on-migrate: true
    locations: classpath:/db/migrations/common,classpath:/db/migrations/${ENV:pro}

#r2dbc:
#  migrate:
#    resources-paths: classpath:/db/migrations/common/*.sql

logging:
  level:
    root: ${LOG_LEVEL_ROOT}
    com.diegosaldiaz.itx.pvp: ${LOG_LEVEL_ITX_PVP}
    org.springframework: ${LOG_LEVEL_SPRING_FRAMEWORK}
    org.hibernate.SQL: ${LOG_LEVEL_HIBERNATE_SQL}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOG_LEVEL_HIBERNATE_BASIC_BINDER}
