server:
  port: 8882
  shutdown: graceful
  compression:
    enabled: true

spring:
  application:
    name: itx-pvp-reactive
  main:
    web-application-type: reactive
  r2dbc:
    url: ${R2DBC_URI}
  flyway:
    url: ${JDBC_URI}
    baseline-on-migrate: true
    locations: classpath:/db/migrations/common,classpath:/db/migrations/${ENV:pro}

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    root: ${LOG_LEVEL_ROOT:error}
    com.diegosaldiaz.inditex.pvp.reactive: ${LOG_LEVEL_ITX_PVP:info}
    org.springframework: ${LOG_LEVEL_SPRING_FRAMEWORK:info}
